-- liquibase formatted sql

-- changeset laserova:1

CREATE TABLE user_entity (
	id int4 generated by default as identity,
	first_name varchar(255) not NULL,
	last_name varchar(255) not NULL,
	email varchar(255) not NULL,
	phone varchar(255) not NULL,
	image_entity_id int4 NULL,
	password varchar(255),
	role varchar(255),
	primary key (id)

);

CREATE TABLE comment_entity (
	id int4 generated by default as identity,
	created_at_inst timestamp NOT NULL,
	comment_text varchar(64) NOT NULL,
	ad_id int4 NOT NULL,
	author_id int4 NOT NULL,
	primary key (id)
);

CREATE TABLE ad_entity (
	id int4 generated by default as identity,
	description varchar(255) NOT NULL,
	image_entity_id int4 NOT NULL,
	price int4 NOT NULL,
	title varchar(255) NOT NULL,
	author_id int4 NOT NULL,
	primary key (id)
);

CREATE TABLE image_entity (
    id int4 generated by default as identity,
    file_path text,
    primary key (id)
);

alter table user_entity add constraint fk_user_to_image FOREIGN KEY (image_entity_id) references image_entity;

alter table comment_entity add constraint comment_user FOREIGN KEY (author_id) references user_entity;
alter table comment_entity add constraint comment_ad FOREIGN KEY (ad_id) references ad_entity;

alter table ad_entity add constraint fk_ad_to_user FOREIGN KEY (author_id) references user_entity;
alter table ad_entity add constraint fk_ad_to_image FOREIGN KEY (image_entity_id) references image_entity;
